src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
class Messages
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    private ?Utilisateur $utilisateur_send = null;

    #[ORM\ManyToOne(inversedBy: 'message')]
    private ?Utilisateur $utilisateur_receive = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $lu = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $bien = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at = null): self
    {
        $this->create_at = new \DateTimeImmutable;

        return $this;
    }

    public function getUtilisateurSend(): ?Utilisateur
    {
        return $this->utilisateur_send;
    }

    public function setUtilisateurSend(?Utilisateur $utilisateur_send): self
    {
        $this->utilisateur_send = $utilisateur_send;

        return $this;
    }

    public function getUtilisateurReceive(): ?Utilisateur
    {
        return $this->utilisateur_receive;
    }

    public function setUtilisateurReceive(?Utilisateur $utilisateur_receive): self
    {
        $this->utilisateur_receive = $utilisateur_receive;

        return $this;
    }

    public function getLu(): ?int
    {
        return $this->lu;
    }

    public function setLu(?int $lu): self
    {
        $this->lu = $lu;

        return $this;
    }

    public function getBien(): ?int
    {
        return $this->bien;
    }

    public function setBien(?int $bien): self
    {
        $this->bien = $bien;

        return $this;
    }
}

src/Entity/UserBan.php
<?php

namespace App\Entity;

use App\Repository\UserBanRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserBanRepository::class)]
class UserBan
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profil = null;

    #[ORM\Column(length: 3, nullable: true)]
    private ?string $sexe = null;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Favoris::class)]
    private Collection $favoris;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Commentaires::class)]
    private Collection $commentaires;

    #[ORM\OneToMany(mappedBy: 'utilisateur_send', targetEntity: Messages::class)]
    private Collection $messages;

    #[ORM\OneToMany(mappedBy: 'utilisateur_receive', targetEntity: Messages::class)]
    private Collection $message;

    #[ORM\Column]
    private ?\DateTimeImmutable $update_at = null;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Administrateur::class)]
    private Collection $admin;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Proprietaires::class)]
    private Collection $proprio;

    public function __construct()
    {
        $this->favoris = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->message = new ArrayCollection();
        $this->admin = new ArrayCollection();
        $this->proprio = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at = null): self
    {
        $this->create_at = new \DateTimeImmutable;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getProfil(): ?string
    {
        return $this->profil;
    }

    public function setProfil(?string $profil): self
    {
        $this->profil = $profil;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(?string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    /**
     * @return Collection<int, Favoris>
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Favoris $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris->add($favori);
            $favori->setUtilisateur($this);
        }

        return $this;
    }

    public function removeFavori(Favoris $favori): self
    {
        if ($this->favoris->removeElement($favori)) {
            // set the owning side to null (unless already changed)
            if ($favori->getUtilisateur() === $this) {
                $favori->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaires>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setUtilisateur($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUtilisateur() === $this) {
                $commentaire->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setUtilisateurSend($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getUtilisateurSend() === $this) {
                $message->setUtilisateurSend(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessage(): Collection
    {
        return $this->message;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeImmutable $update_at = null): self
    {
        $this->update_at = new \DateTimeImmutable;

        return $this;
    }

    /**
     * @return Collection<int, Administrateur>
     */
    public function getAdmin(): Collection
    {
        return $this->admin;
    }

    public function addAdmin(Administrateur $admin): self
    {
        if (!$this->admin->contains($admin)) {
            $this->admin->add($admin);
            $admin->setUtilisateur($this);
        }

        return $this;
    }

    public function removeAdmin(Administrateur $admin): self
    {
        if ($this->admin->removeElement($admin)) {
            // set the owning side to null (unless already changed)
            if ($admin->getUtilisateur() === $this) {
                $admin->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Proprietaires>
     */
    public function getProprio(): Collection
    {
        return $this->proprio;
    }

    public function addProprio(Proprietaires $proprio): self
    {
        if (!$this->proprio->contains($proprio)) {
            $this->proprio->add($proprio);
            $proprio->setUtilisateur($this);
        }

        return $this;
    }

    public function removeProprio(Proprietaires $proprio): self
    {
        if ($this->proprio->removeElement($proprio)) {
            // set the owning side to null (unless already changed)
            if ($proprio->getUtilisateur() === $this) {
                $proprio->setUtilisateur(null);
            }
        }

        return $this;
    }
}

templates/security/_form.html.twig
<div class="card-body">
    {{ form_start(form) }}
    <div class="input-group mb-3">
        <span class="input-group-text" id="nom-addon"><i class="fa-solid fa-user"></i></span>
        {{ form_widget(form.nom, {attr: {placeholder: 'Nom complet', 'aria-describedby': 'nom-addon', 'aria-label': 'Nom'}}) }}
    </div>{{ form_errors(form.nom) }}

    <div class="row mb-3">
        <div class="col-md-6">
            <div class="input-group mb-3">
                <span class="input-group-text" id="email-addon"><i class="fa-solid fa-envelope"></i></span>
                {{ form_widget(form.email, {attr: {placeholder: 'Email', 'aria-describedby': 'email-addon', 'aria-label': 'Email'}}) }}
            </div>{{ form_errors(form.email) }}
        </div>
        <div class="col-md-6">
            <div class="input-group mb-3">
                <span class="input-group-text" id="pass-addon"><i class="fa-solid fa-lock"></i></span>
                {{ form_widget(form.password, {attr: {placeholder: 'Mot de passe', 'aria-describedby': 'pass-addon', 'aria-label': 'Password'}}) }}
                <span class="input-group-text" id="eye-addon" onclick="togglePass()"><i class="fa-solid fa-eye" id="eyeCon"></i></span>
            </div>{{ form_errors(form.password) }}
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-md-6">
            <label class="form-check-label" id="sexe-addon">Civilité: &nbsp;</label>
            {{ form_widget(form.sexe, {attr: {class: 'form-check-inline'}}) }}
            {{ form_errors(form.sexe) }}
        </div>
        <div class="col-md-6">
            {{ form_widget(form.profil) }}
            {{ form_errors(form.profil) }}
        </div>
    </div>

    {{ form_row(form.valider, {attr: {class: 'w-100 bg-primary my-3 fw-bold'}}) }}
    {{ form_end(form) }}
</div>

templates/security/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Edition - {{ user.nom }} {% endblock %}

{% block style %}
    <style>
        #eye-addon, .form-check-label {
            cursor: pointer;
        }
        .lightbox img, .lightbox i {
            border: 1px solid #FFF;
            box-shadow: 0px 0px 8px rgba(0, 0, 0, .3);
            width: 10vw;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container-md mx-auto ">
        <div class="card mx-auto">
            <div class="card-header">
                <h1 class="mb-3 h3 fw-bold text-center">Bienvenue sur votre panel</h1>
            </div>
            {% if edit is defined %}
                <div class="edit m-4">
                    {% if user.profil %}
                        <div class="lightbox">
                            <img src="{{ asset('assets/img/' ~ user.profil) }}" alt="{{ user.nom }}" />
                        </div>
                    {% else %}
                        <div class="lightbox">
                            <i class="fa-solid fa-user fa-3x"></i>
                        </div>
                    {% endif %}
                    <ul class="list-group my-3">
                        <li class="list-group-item">Nom : {{ user.nom }}</li>
                        <li class="list-group-item">Email : {{ user.email }}</li>
                        <li class="list-group-item">Sexe : {% if user.sexe == 'H' %} Homme {% else %} Femme {% endif %}</li>
                        <li class="list-group-item">Statut : {% if is_granted('ROLE_PROPRIO') %} Propriétaires de biens immobiliers. (<a href="{{ path('biens') }}">Voir mes biens</a>)
                            {% elseif is_granted('ROLE_ADMIN') %} Administrateur {% else %} Utilisateur {% endif %}</li>
                        <li class="list-group-item">Compte crée le : {{ user.createAt|date('d/m/y à H:i')  }}</li>
                    </ul>
                    <form method="post" action="{{ path('app_admin_delete', {id: user.id, user: 'user'}) }}"
                          onsubmit='return confirm("Voulez-vous vraiment supprimer votre compte?")'>
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}"/>
                        <a href="{{ path('app_edit', {edit: 1}) }}" class="btn btn-primary"><i class="fa-solid fa-user-pen"></i> Editer</a>
                        <button class="btn btn-danger"><i class="fa-solid fa-trash-can"></i> Supprimer mon compte</button>
                    </form>
                </div>
            {% else %} {{ include('security/_form.html.twig') }} {% endif %}
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        function togglePass() {
            let $pass = $('#utilisateur_password'), $eye = $('#eyeCon');
            if ($eye.hasClass('fa-eye')) {
                $eye.removeClass('fa-eye')
                $eye.addClass('fa-eye-slash')
                $pass.attr('type', 'text')
            }
            else {
                $eye.removeClass('fa-eye-slash')
                $eye.addClass('fa-eye')
                $pass.attr('type', 'password')
            }
        }
    </script>
{% endblock %}

templates/security/favori.html.twig
{% extends 'base.html.twig' %}

{% block title %} Favori - {{ user.nom }} {% endblock %}

{% block body %}
    <div class="container-md mx-auto ">
        <div class="card mx-auto">
            <div class="card-header">
                <h4 class="mb-3 fw-bold text-center"> Inbox </h4>
            </div>
            <div class="card-body">
                {% if retour is defined %}
                    <p class="text-muted">{{ retour }}</p>
                {% endif %}

                {% if message is defined %}
                    {% for mess in message %}
                        {% if user.id == mess.utilisateurSend.id %}
                            <div class="gauche bg-info text-end p-3 my-1">{{ mess.contenu }}
                                <span class="text-muted">Envoyé le {{ mess.createAt|date('d/m/Y à H:i') }}</span>
                            </div>
                        {% endif %}
                        {% if user.id == mess.utilisateurReceive.id %}
                            <div class="droite bg-warning p-3 my-1">{{ mess.contenu }}
                                <span class="text-muted">Envoyé le {{ mess.createAt|date('d/m/Y à H:i') }}</span>
                            </div>
                        {% endif %}
                    {% endfor %}

                    <form method="post" action="{{ path('app_message.send', {id: user.id, receive: receive.id}) }}" class="d-inline-block">
                        <div class="my-3 chat">
                            <label for="msg" class="form-label">Message</label>
                            <textarea class="form-control" id="msg" rows="3" name="mess"></textarea>
                            <button class="btn btn-primary w-100 my-2" type="submit">Envoyer</button>
                        </div>
                    </form>
                {% endif %}

                {% if users is defined %}
                    <table class="table table-striped">
                        {% for user1 in users %}
                            <tr>
                                <td><a href="{{ path('app_message.send', {id: user.id, receive: user1.id}) }}">{{ user1.nom }}</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %} Connexion - Franck Immo {% endblock %}

{% block style %}
    <style>
        #eye-addon, .form-check-label {
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container-md mx-auto ">
        <div class="card mx-auto">
            <div class="card-header">
                <h1 class="mb-3 fw-bold text-center">Connectez-vous</h1>
            </div>
            <div class="card-body">
                <form method="post">
                    {% if error %}
                        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                    {% endif %}

                    {% if app.user %}
                        <div class="mb-3">
                            Vous êtes connectés en tant que {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Deconnexion</a>
                        </div>
                    {% endif %}

                    <div class="input-group mb-3">
                        <span class="input-group-text" id="email-addon"><i class="fa-solid fa-envelope"></i></span>
                        <input type="email" placeholder="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" aria-label="Email" aria-describedby="email-addon" autocomplete="email" required autofocus />
                    </div>

                    <div class="input-group mb-3">
                        <span class="input-group-text" id="pass-addon"><i class="fa-solid fa-lock"></i></span>
                        <input type="password" name="password" id="inputPassword" placeholder="Mot de passe" class="form-control" autocomplete="current-password" aria-label="Password" aria-describedby="pass-addon" required>
                        <span class="input-group-text" id="eye-addon" onclick="togglePass()"><i class="fa-solid fa-eye" id="eyeCon"></i></span>
                    </div>

                    <div class="form-check">
                        <input type="checkbox" name="_remember_me" class="form-check-input" id="remember">
                        <label class="form-check-label" for="remember">Se rappeler de moi</label>
                    </div>
                    <div class="mb-3 text-end">
                        <a href="/forgot_pass"> Mot de passe oublié </a>
                    </div>

                    <input type="hidden" name="_csrf_token"
                           value="{{ csrf_token('authenticate') }}"
                    >
                    <button class="btn btn-lg btn-primary w-100" type="submit">
                        Se connecter
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        function togglePass() {
            let $pass = $('#inputPassword'), $eye = $('#eyeCon');
            if ($eye.hasClass('fa-eye')) {
                $eye.removeClass('fa-eye')
                $eye.addClass('fa-eye-slash')
                $pass.attr('type', 'text')
            }
            else {
                $eye.removeClass('fa-eye-slash')
                $eye.addClass('fa-eye')
                $pass.attr('type', 'password')
            }
        }
    </script>
{% endblock %}

templates/security/message.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title }} - {{ app.user.nom }} {% endblock %}

{% block style %}
    <style>
        div.gallerie .gallery li {
            list-style: none;
            height: 130px;
            flex-grow: 1;
        }
        .message div.card {
            max-height: 80vh;
            overflow: scroll;
        }

        .message-feed.right > .pull-right {
            margin-left: 15px;
        }
        .message-feed:not(.right) .mf-content {
            background: #03a9f4;
            color: #fff;
            box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12);
        }

        .message-feed.right .mf-content {
            background: #eee;
        }

        .message-feed.right {
            text-align: right;
        }

        .mf-content {
            display: inline-block;
            padding: 12px 17px 13px;
            border-radius: 2px;
            max-width: 95%;
        }

        .media-body, .img-box {
            display: inline-block;
            vertical-align: top;
        }

        .media-body {
            max-width: 80%;
        }

        .mf-date {
            display: block;
            color: #B3B3B3;
            margin-top: 7px;
        }

        .mf-date > i {
            font-size: 14px;
            line-height: 100%;
            position: relative;
            top: 1px;
        }
        .img-avatar {
            height: 37px;
            width: 37px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container-md mx-auto message">
        <div class="card mx-auto">
            <div class="card-header"> <h4 class="mb-3 fw-bold text-center">
                {% if favs is defined %} Liste de vos favoris {% else %}
                        Inbox {% if receive is defined %}- {{ receive.nom }} {% endif %}
                {% endif %}</h4>
            </div>
            <div class="card-body">
                {% if retour is defined %}
                    <p class="text-muted">{{ retour }}</p>
                {% endif %}

                {% if favs is defined and favs != 0 %}
                    <table class="table table-striped">
                        <tr>
                            <th>Noms</th>
                            <th>Propriétaire</th>
                            <th>Prix</th>
                            <th>Actions</th>
                        </tr>
                        {% for fav in favori %}
                            <tr>
                                <td><a href="{{ path('biens.detail', {id: fav.biens.id}) }}"> {{ fav.biens.nom }} </a></td>
                                <td> {{ fav.biens.proprietaires.utilisateur.nom }} </td>
                                <td> {{ fav.biens.prix }}&euro;</td>
                                <td>
                                    <form method="post" action="{{ path('app_fav_del', {id: fav.id}) }}"
                                          class="d-inline-block">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fav.id) }}"/>
                                        <button class="btn btn-danger"><i class="fa-solid fa-trash-can"></i> Supprimer
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}

                {% if message is defined %}
                    <form method="post" action="{{ path('app_message.send', {receive: receive.id}) }}" class="send_mess sticky-top">
                        <div class="input-group mb-1 chat">
                            <input type="text" name="mess" class="form-control" placeholder="Entrer votre message ici ..." aria-label="Message text" aria-describedby="mess-button">
                            <button class="btn btn-primary" type="submit" id="mess-button">
                                <i class="fa-regular fa-paper-plane fa-lg"></i></i>
                            </button>
                        </div>
                    </form>
                    {% for mess in message %}
                        {% if app.user.id == mess.utilisateurSend.id %}
                            <div class="message-feed py-1 right">
                                <div class="media-body">
                                    <div class="mf-content"> {{ mess.contenu }}
                                        {% if mess.bien > 0 %}
                                            <br/><a href="{{ path('biens.detail', {id: mess.bien}) }}">Voir le bien</a>
                                        {% endif %}
                                        <form method="post" action="{{ path('app_message_del', {user: mess.utilisateurReceive.id, id: mess.id}) }}"
                                              class="">
                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mess.id) }}"/>
                                            <button class="btn btn-close btn-outline-danger" aria-label="Close"></button>
                                        </form>
                                    </div>
                                    <small class="mf-date"><i
                                                class="fa-regular fa-clock"></i> {{ mess.createAt|date('d/m/Y à H:i') }}
                                    </small>
                                </div>
                                <div class="pull-right img-box">
                                    {% if mess.utilisateurSend.profil %}
                                        <img src={{ asset('assets/img/' ~ mess.utilisateurSend.profil) }} alt="{{ mess.utilisateurSend.nom }}"
                                             class="img-avatar rounded-circle"/>
                                    {% else %}
                                        <i class="fa-solid fa-user img-avatar rounded-circle"></i>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                        {% if app.user.id == mess.utilisateurReceive.id %}
                            <div class="message-feed py-1 media">
                                <div class="pull-left img-box">
                                    {% if mess.utilisateurSend.profil %}
                                        <img src={{ asset('assets/img/' ~ mess.utilisateurSend.profil) }} alt="{{ mess.utilisateurSend.nom }}"
                                             class="img-avatar rounded-circle"/>
                                    {% else %}
                                        <i class="fa-solid fa-user img-avatar rounded-circle"></i>
                                    {% endif %}
                                </div>
                                <div class="media-body">
                                    <div class="mf-content"> {{ mess.contenu }}
                                        {% if mess.bien > 0 %}
                                            <br/><a href="{{ path('biens.detail', {id: mess.bien}) }}"
                                                    class="text-warning">Voir le bien</a>
                                        {% endif %}
                                    </div>
                                    <small class="mf-date"><i
                                                class="fa-regular fa-clock"></i> {{ mess.createAt|date('d/m/Y à H:i') }}
                                    </small>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}

                {% if messUser is defined %}
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>Noms</th>
                            <th>Email</th>
                        </tr>
                        {% for mes in messUser %}
                            <tr>
                                <td><a href="{{ path('app_message.send', {receive: mes.id}) }}">
                                        {{ mes.nom }}
                                    </a>
                                    {% if app.session.get(mes.id) and app.session.get(mes.id) > 0 %}
                                        <span class="badge bg-danger ms-2"> {{ app.session.get(mes.id) }} </span>
                                    {% endif %}
                                </td>
                                <td> {{ mes.email }} </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}